services:
  zenoh_broker:
    image: eclipse/zenoh:latest
    container_name: zenoh_broker
    ports:
      - "7447:7447"
    networks:
      - zenoh_network
    command: ["--listen", "tcp/0.0.0.0:7447"]

  indbf:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "INDBF/main.py"]
    depends_on:
      - zenoh_broker
    networks:
      - zenoh_network

  ndppf:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "NDPPF/preprocess.py"]
    depends_on:
      - indbf
    networks:
      - zenoh_network

  endbf:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "eNDBF/main.py"]
    depends_on:
      - ndppf
    ports:
      - "7448:7448"
    networks:
      - zenoh_network

  fl_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "FLAD/FLServer/server_driver.py"]
    ports:
      - "5000:5000"
    depends_on:
      - zenoh_broker
    networks:
      - zenoh_network

  fl_client:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "FLAD/FLClient/client_driver.py"]
    depends_on:
      - fl_server
    networks:
      - zenoh_network

networks:
  zenoh_network:
    driver: bridge
